words = [
    "clippy",
    "dotenv",
    "dtolnay",
    "fdfind",
    "gha",
    "isready",
    "justfile",
    "rustfmt",
    "swatinem",
    "xzf",
]
ignore_paths = ["Cargo.lock"]
ignore_patterns = ['\b[a-fA-F0-9]{64}\b']
