words = [
    "clippy",
    "direnv",
    "dotenv",
    "dtolnay",
    "envrc",
    "fdfind",
    "gha",
    "isready",
    "justfile",
    "nicknovitski",
    "nixbuild",
    "nixos",
    "nixpkgs",
    "oxalica",
    "pkgs",
    "rustfmt",
    "swatinem",
    "tombi",
    "xzf",
]
ignore_paths = [
    "Cargo.lock",
    "flake.lock",
]
ignore_patterns = ['\b[a-fA-F0-9]{64}\b']
