FROM rust:1.91.1-alpine3.22

WORKDIR /test

# Pre-build dependencies so they're cached even if the app code changes
COPY Cargo.toml Cargo.lock ./
RUN mkdir src \
  && echo "fn main() {}" > src/main.rs \
  && cargo test --no-run --workspace --all-targets \
  && rm -rf src

# Copy the real code
COPY src src
RUN touch src/main.rs

ENTRYPOINT ["cargo", "test"]
CMD ["--frozen", "--workspace", "--all-targets"]
